baseurl      = "//kmfrick.vision"
title        = "Kevin Michael Frick"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "BSc Computer Engineering student - Collegio Superiore, University of Bologna"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Metadata mostly used in document's head
  description = "Kevin's home page"
  keywords = "computer vision, machine learning, graph theory, statistics, software engineering"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  
  [params.portrait]
    path = "/img/kevin.jpg"
    alt = "Kevin"

  # Social icons

  [[params.social]]
    name = "github"
    url  = "https://github.com/kmfrick"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/kmfrick"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Kevin Michael Frick"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cat .plan"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"


  [[menu.main]]
    identifier = "college"
    name       = "College"
    url        = "/college/"
  
  [[menu.main]]
    identifier = "git"
    name       = "Git"
    url        = "https://git.kmfrick.vision/kmfrick"

  [[menu.main]]
    identifier = "pgp"
    name       = "PGP"
    url        = "pgp.txt"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
